package com.au.gonannysingleactivity.objects

object Constants {

    const val KEY_FOR_ID = "KEY_FOR_ID"
    const val KEY_FOR_FRAGMENT_REPLACEMENT = "KEY_FOR_STRING"
    const val KEY_SELECT_DATE_TIME = "KEY_SELECT_DATE_TIME"
    const val KEY_SELECT_DURATION = "KEY_SELECT_DURATION"
    const val KEY_SELECT_ADDRESS = "KEY_SELECT_ADDRESS"
    const val KEY_EDIT_ADDRESS = "KEY_EDIT_ADDRESS"
    const val KEY_SELECT_MAILING_ADDRESS = "KEY_SELECT_MAILING_ADDRESS"
    const val KEY_SELECT_KIDS = "KEY_SELECT_KIDS"
    const val KEY_GET_PRICING = "KEY_GET_PRICING"
    const val KEY_USER_SHARED_PREFERENCE = "KEY_USER_SHARED_PREFERENCE"
    const val KEY_HOME = "ParentHomeFragment"
    const val KEY_COMPLETE_SIGN_UP = "CompleteSignUpFragment"
    const val KEY_ADD_KID_INFO = "AddKidInfoFragment"
    const val KEY_ADD_ADDRESS = "AddAddressFragment"
    const val KEY_ADD_CARD = "AddCardFragment"
    const val KEY_SIGN_AGREEMENT = "SignAgreementFragment"
    const val KEY_BROADCAST = "keyBroadcastSelectInfo"
    const val KEY_FROM_WHERE = "KEY_FROM_WHERE"
    const val KEY_SHOW_PROFILE = "KEY_SHOW_PROFILE"
    const val KEY_SETTING_KIDS = "KEY_SETTING_KIDS"
    const val KEY_SETTING_USED_HOUR = "KEY_SETTING_USED_HOUR"
    const val KEY_SETTING_ADDRESSES = "KEY_SETTING_ADDRESSES"
    const val KEY_SETTINGS_CARD = "KEY_SETTINGS_CARD"
    const val KEY_SETTING_CHANGE_PASSWORD = "KEY_SETTING_CHANGE_PASSWORD"
    const val KEY_SETTING_CONTACT_US = "KEY_SETTING_CONTACT_US"
    const val KEY_FAQ = "KEY_FAQ"
    const val KEY_SHOW_BOOKING_DETAIL = "KEY_SHOW_BOOKING_DETAIL"
    const val KEY_ADD_PHOTO_FRAGMENT = "KEY_ADD_PHOTO_FRAGMENT"
    const val KEY_ADD_DOCUMENTS = "KEY_ADD_DOCUMENTS"
    const val KEY_WORKING_HOURS = "KEY_WORKING_HOURS"
    const val KEY_LINK_BANK_ACCOUNT = "KEY_ADD_BANK_ACCOUNT"
    const val KEY_CHAT_FRAGMENT = "KEY_CHAT_FRAGMENT"
    const val KEY_ADD_WWCC_FRAGMENT = "KEY_ADD_WWCC_FRAGMENT"
    const val KEY_EARNINGS_FRAGMENT = "KEY_EARNINGS_FRAGMENT"
    const val KEY_WORKING_HOUR_FRAGMENT = "KEY_WORKING_HOUR_FRAGMENT"
    const val KEY_LINKED_BANK_ACC_FRAGMENT = "KEY_LINKED_BANK_ACC_FRAGMENT"
    const val KEY_PHOTOS_FRAGMENT = "KEY_PHOTOS_FRAGMENT"
    const val KEY_DOCUMENTS_FRAGMENT = "KEY_DOCUMENTS_FRAGMENT"

    const val oneWeekInMilli = 604800000
    const val KEY_WWCC_BROADCAST = "KEY_WWCC_BROADCAST"

    const val BASE_URL = "http://gonanny.com.au:3001/api/"
    const val BASE_IMAGE_URL = "http://gonanny.com.au:3001/api/do/image?filename="
    const val sharedPreferencesKey = "com.au.gonannysingleactivity.utils"
    const val ADMIN_EMAIL_ADDRESS = "admin@gonanny.com.au"
    const val PATH_FOR_SOCKET =  "http://gonanny.com.au:3001"
//    const val FCM_ID = "1:342552141685:android:66d1727768b7bed4d23d3c"
}